"""Generate summary visuals for model predictions."""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

FIGURE_FILENAMES = {
    "distribution": "distribution_p_final.png",
    "monthly_mean": "monthly_mean_p_final.png",
    "alert_counts": "alert_counts.png",
    "top_table": "top_predictions.csv",
}


def _prepare_dataframe(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    if "TA_YM" in df.columns:
        df["TA_YM"] = pd.to_datetime(df["TA_YM"], errors="coerce")
    if "ENCODED_MCT" in df.columns:
        df["ENCODED_MCT"] = df["ENCODED_MCT"].astype(str)
    return df.dropna(subset=["p_final"])


def plot_distribution(df: pd.DataFrame, output_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(df["p_final"], bins=30, color="#4C72B0", edgecolor="white")
    ax.set_title("Distribution of final risk scores")
    ax.set_xlabel("p_final")
    ax.set_ylabel("Count")
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def plot_monthly_mean(df: pd.DataFrame, output_path: Path) -> None:
    if "TA_YM" not in df.columns:
        return
    monthly = (
        df.dropna(subset=["TA_YM"])
        .groupby(df["TA_YM"].dt.to_period("M"))
        ["p_final"].mean()
        .sort_index()
    )
    if monthly.empty:
        return
    fig, ax = plt.subplots(figsize=(9, 5))
    monthly.index = monthly.index.to_timestamp()
    ax.plot(monthly.index, monthly.values, marker="o", color="#DD8452")
    ax.set_title("Monthly average of final risk scores")
    ax.set_xlabel("Month")
    ax.set_ylabel("Average p_final")
    ax.grid(True, alpha=0.3)
    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def plot_alert_counts(df: pd.DataFrame, output_path: Path) -> None:
    if "Alert" not in df.columns:
        return
    counts = df["Alert"].value_counts().reindex(["GREEN", "YELLOW", "ORANGE", "RED"], fill_value=0)
    fig, ax = plt.subplots(figsize=(7, 5))
    colors = {"GREEN": "#55A868", "YELLOW": "#EBC844", "ORANGE": "#EE8F21", "RED": "#C23B22"}
    ax.bar(counts.index, counts.values, color=[colors[c] for c in counts.index])
    ax.set_title("Alert count by severity")
    ax.set_xlabel("Alert level")
    ax.set_ylabel("Number of merchants")
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def export_top_predictions(df: pd.DataFrame, output_path: Path, top_n: int) -> None:
    top = df.sort_values("p_final", ascending=False).head(top_n)
    top.to_csv(output_path, index=False, encoding="utf-8")


def generate_prediction_figures(risk_output_path: Path, output_dir: Path, top_n: int = 20) -> None:
    df = _prepare_dataframe(risk_output_path)
    output_dir.mkdir(parents=True, exist_ok=True)

    plot_distribution(df, output_dir / FIGURE_FILENAMES["distribution"])
    plot_monthly_mean(df, output_dir / FIGURE_FILENAMES["monthly_mean"])
    plot_alert_counts(df, output_dir / FIGURE_FILENAMES["alert_counts"])
    export_top_predictions(df, output_dir / FIGURE_FILENAMES["top_table"], top_n)


def main() -> None:
    parser = argparse.ArgumentParser(description="Create summary figures for risk predictions.")
    parser.add_argument("risk_output", type=Path, help="Path to the risk_output CSV generated by the pipeline")
    parser.add_argument("--output", type=Path, default=Path("figures"), help="Directory to save the figures")
    parser.add_argument("--top", type=int, default=20, help="Number of top predictions to export")
    args = parser.parse_args()

    generate_prediction_figures(args.risk_output, args.output, args.top)


if __name__ == "__main__":
    main()
